# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish ./WindSong/WindSong.csproj -c Release -r win10-x64 -o publish -p:Platform=x64 -p:SelfContained=true -p:PublishSingleFile=true -p:PublishReadyToRun=false -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true

    - name: Install WindowsAppRuntime
      run: |
        $config = Get-Content -Raw config.json | ConvertFrom-Json;
        Invoke-WebRequest -Uri $config.WindowsAppRuntime -OutFile install.exe;
        ./install.exe

    - name: Test
      run: |
        Get-ChildItem -Path publish;
        Write-Host ----------;
        Start-Process -FilePath ./publish/WindSong.exe;
        $p = Get-Process -Name WindSong;
        Start-Sleep -Seconds 3;
        Write-Host "Main window handle: $($p.MainWindowHandle)";
        if ($p.MainWindowHandle -gt 0) {
            Write-Host "Start successfully!" -ForegroundColor Green;
            $null = $p.CloseMainWindow();
        } else {
            Write-Error "Start failed!";
            exit -1;
        }

    - name: Config Ossutil
      run: |
        Invoke-WebRequest https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64.zip -OutFile ${{runner.temp}}/ossutil64.zip
        Expand-Archive -Path ${{runner.temp}}/ossutil64.zip -DestinationPath ${{runner.temp}}
        Move-Item -Path ${{runner.temp}}/ossutil64/ossutil64.exe -Destination C:/Windows/System32/ossutil.exe -Force
        ossutil config -e ${{secrets.OSS_ENDPOINT}} -i ${{secrets.ACCESS_KEY_ID}} -k ${{secrets.ACCESS_KEY_SECRET}}

    - name: Upload to Oss
      run: |
        Compress-Archive -Path publish -DestinationPath windsong-ci.zip
        ossutil cp windsong-ci.zip oss://scighost-xunkong/download/windsong/ -f
